#!/bin/bash
#	Jeremin Freed Meister
#	ISP15
# kontrollib public kausta olemasolu
# parandab õigused
kasutaja=$1
dir=/home/$kasutaja/public/
	if [ -d $dir ]; then
		perm=$(stat -c %a $dir)
		echo "Public kaust on olemas"
	else
	sh ./lisa_public $kasutaja
	echo "Kausta pole olemas"
	echo "Kasutajale $kasutaja loodi public kaust"
	exit
fi
	if [ $perm = "777" ]; then
	echo "Õigused on korras"
	else
	chmod 777 /home/$kasutaja/public/
	echo "Õigused parandatud/muudetud õigeks"
fi
