#!/bin/bash

kuupaev=$(date +%d.%m.%y)

for nimi in $(awk -F'[/:]' '{if ($3 >= 1000 && $3 != 65534) print $1}' /etc/passwd)
do
	if [ -f /backup/$nimi.$kuupaev.tar.bz2 ]; then
		echo "$nimi backup on juba tehtud"
	else
		tar  -PcvjSf /backup/$nimi.$kuupaev.tar.bz2 /home/$nimi
		echo "$nimi backup edukas"
fi
done
